
import { Bot } from './types';

export const BOTS_DATA: Bot[] = [
  {
    id: '1',
    name: 'MusicMaestro',
    avatarUrl: 'https://picsum.photos/seed/music/200',
    description: 'High-quality music bot with playlist support, effects, and 24/7 playback. Bring the beat to your server!',
    tags: ['Music', 'Fun', 'Utility'],
    userCount: 1250000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: true,
  },
  {
    id: '2',
    name: 'AdminGuard',
    avatarUrl: 'https://picsum.photos/seed/admin/200',
    description: 'Powerful moderation bot to keep your server safe. Features auto-moderation, logging, and anti-raid.',
    tags: ['Moderation', 'Security', 'Logging'],
    userCount: 780000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: true,
  },
  {
    id: '3',
    name: 'GameMaster',
    avatarUrl: 'https://picsum.photos/seed/game/200',
    description: 'Engage your community with fun games like trivia, chess, and hangman. Leaderboards included!',
    tags: ['Gaming', 'Fun', 'Community'],
    userCount: 520000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: false,
  },
  {
    id: '4',
    name: 'MemeLord',
    avatarUrl: 'https://picsum.photos/seed/meme/200',
    description: 'Serves the freshest memes from across the internet. Customizable meme sources and commands.',
    tags: ['Memes', 'Fun', 'Social'],
    userCount: 2300000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: true,
  },
  {
    id: '5',
    name: 'CodeHelper',
    avatarUrl: 'https://picsum.photos/seed/code/200',
    description: 'A utility bot for developers. Run code snippets in over 20 languages directly in Discord.',
    tags: ['Utility', 'Development', 'Tools'],
    userCount: 95000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: true,
  },
  {
    id: '6',
    name: 'WelcomeWave',
    avatarUrl: 'https://picsum.photos/seed/welcome/200',
    description: 'Create custom welcome messages and banners for new members. Assign roles automatically on join.',
    tags: ['Welcomer', 'Utility', 'Community'],
    userCount: 450000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: false,
  },
  {
    id: '7',
    name: 'PollMaster',
    avatarUrl: 'https://picsum.photos/seed/poll/200',
    description: 'Easily create simple or advanced polls with multiple choices and timed endings.',
    tags: ['Utility', 'Polls', 'Community'],
    userCount: 180000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: true,
  },
  {
    id: '8',
    name: 'ServerStats',
    avatarUrl: 'https://picsum.photos/seed/stats/200',
    description: 'Display your server stats like member count, online users, and more in custom channels.',
    tags: ['Utility', 'Server Management'],
    userCount: 310000,
    inviteUrl: 'https://discord.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&scope=bot&permissions=8',
    isVerified: true,
  },
];
